#! /usr/bin/env python

import rospy
from dartbox.node import DartNode


if __name__ == "__main__":
    node = DartNode()
    rospy.init_node("dart_node")
    rospy.loginfo("dartbox: initialized DartNode")

    rospy.loginfo("dartbox: starting game...")
    node.game.run()

    # not using rospy.spin(), hence the process terminates
    rospy.loginfo("dartbox: shutting down...")
